[project]
name = "project-euler-solutions"
version = "0.1.0"
description = "My personal solutions to Project Euler problems."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.4.2",
]